### ISSUE TITLE
Named export 'easepick' not found. Issue with vitejs starting from 5.0.8

### ISSUE THREAD

**Issue by temqua** [easepick/easepick#250]
**Describe the bug**
I use [SvelteKit](kit.svelte.dev) for production development. I found `easepick` really beautiful and smart solution and added to project. Since [vite](vitejs.dev) 5.0.8 version, I started seeing next errors:
```
00:02:32 [vite] Error when evaluating SSR module /src/routes/(app)/+layout.svelte: failed to import "@easepick/core"
|- SyntaxError: [vite] Named export 'easepick' not found. The requested module '@easepick/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@easepick/core';
const {easepick} = pkg;

at analyzeImportedModDifference (file:///home/artem/Work/control-panel/node_modules/.pnpm/vite@5.3.4_@types+node@20.14.9_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:52539:15)
    at nodeImport (file:///home/artem/Work/control-panel/node_modules/.pnpm/vite@5.3.4_@types+node@20.14.9_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:53542:5)
    at async ssrImport (file:///home/artem/Work/control-panel/node_modules/.pnpm/vite@5.3.4_@types+node@20.14.9_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:53394:16)
```
So I stuck with `5.0.7` version of vite and can't update. Could you please look at this? 
**To Reproduce**
1. Just create an application using these bunch of commands
```bash
npm create svelte@latest my-app
cd my-app
npm install
npm run dev
```
2. Then install easepick and try to add it e.g. in main +page.svelte. It doesn't depends which package manager to use: both with `npm` and `pnpm` th error appears.

**Comment by shezard** [comment]
I had the same issue, i fixed it this way:

```js
const easePickCore = await import('@easepick/core');
const { easepick } = easePickCore;
```

**Comment by shreyasrama** [comment]
It appears this was part of vite 5 breaking changes but was indirectly working until 5.0.8: https://github.com/vitejs/vite/issues/15403

You can try the refactors mentioned here: https://vitejs.dev/guide/migration.html#ssr-externalized-modules-value-now-matches-production

e.g. before `onMount`

```ts
import * as easepick from '@easepick/bundle';
...

```
